### ISSUE TITLE
traning

### ISSUE THREAD

**Issue by sankar-mukherjee** [egorsmkv/radtts-istftnet#1]
thanks for the repository. How did you train the radtts? from the original repo?

**Comment by egorsmkv** [comment]
I have forked the original RADTTS's repo and made changes for Ukrainian

The fork is here - https://github.com/egorsmkv/radtts

**Comment by egorsmkv** [comment]
Look on my notes in the repo for commands I have used during the training - https://github.com/egorsmkv/radtts/blob/main/NOTES.txt
